# Generated by Django 5.0.7 on 2024-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='working_year_number',
            field=models.IntegerField(verbose_name='Working year number'),
        ),
    ]
