# Generated by Django 5.0.7 on 2024-08-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone'),
        ),
    ]
