# Generated by Django 5.1.2 on 2024-10-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_realestate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ceo',
            field=models.BooleanField(default=False, verbose_name='CEO'),
        ),
    ]
