# Generated by Django 5.0.7 on 2024-08-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_realestate_description_realestate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
