# Generated by Django 5.0.7 on 2024-08-15 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_realestate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileOfSellerOrRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_or_agent', models.CharField(choices=[('OW', 'Owner'), ('AG', 'Agent')], max_length=10, verbose_name='Owner Or Agent')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('home_phone', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)], verbose_name='Home Phone')),
                ('birth_year', models.DateField(verbose_name='Birth Year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
