# Generated by Django 5.0.7 on 2024-08-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profileofsellerorrealestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileofsellerorrealestate',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
