# Generated by Django 5.1.2 on 2024-11-08 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_pid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Borrower_PID')),
                ('bank_account_number', models.CharField(max_length=12, verbose_name='Bank Account Number')),
                ('bank', models.CharField(choices=[('bank_of_america', 'Bank Of America'), ('JPmorgan_chase', 'JPmorgan Chase'), ('td_bank', 'TD Bank'), ('first_citizen_bank', 'First Citizen Bank'), ('citibank', 'CitiBank'), ('wells_fargo_bank', 'Wells Fargo Bank'), ('pnc_bank', 'PNC Bank')], default='bank_of_america', max_length=50, verbose_name='Bank')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('has_got_loan_service', models.BooleanField(default=False, verbose_name='has got loan service')),
                ('activate_code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Activate Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='LoanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(choices=[(25000, '25,000.00'), (50000, '50,000.00'), (75000, '75,000.00'), (100000, '100,000.00'), (125000, '125,000.00'), (150000, '150,000.00'), (175000, '175,000.00'), (200000, '200,000.00')], default=25000, verbose_name='Price')),
                ('refund_month', models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (12, '12')], default=4, verbose_name='Refund Month')),
                ('start_time', models.DateField(verbose_name='Start time')),
                ('end_time', models.DateField(verbose_name='End time')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Percentage')),
                ('total_refund', models.FloatField(blank=True, null=True, verbose_name='Total Refund')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_service', to='loan_service.borrower', verbose_name='Borrower')),
            ],
        ),
    ]
