# Generated by Django 5.1.2 on 2024-11-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('successful', 'Successful')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
