# Generated by Django 5.1.2 on 2024-11-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0004_alter_borrower_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanservice',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='loanservice',
            name='start_time',
            field=models.DateField(auto_now_add=True, verbose_name='Start time'),
        ),
    ]
