# Generated by Django 5.1.2 on 2024-11-25 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_service', '0005_alter_loanservice_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanservice',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Code'),
        ),
    ]
