# Generated by Django 5.0.7 on 2024-07-20 06:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Address')),
                ('meter', models.IntegerField(verbose_name='Meter')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Postal Code')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(verbose_name='Description')),
                ('floor', models.PositiveIntegerField(verbose_name='Floors')),
                ('beds', models.PositiveIntegerField(verbose_name='Beds')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('realestate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='account.realestate', verbose_name='RealEstate')),
            ],
        ),
    ]
