# Generated by Django 5.0.7 on 2024-07-20 08:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField(verbose_name='Final Price')),
                ('rental_start_date', models.DateField(verbose_name='Rental Start Date')),
                ('rental_end_date', models.DateField(verbose_name='Rental End Date')),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_landlord', to=settings.AUTH_USER_MODEL, verbose_name='LandLord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_tenant', to=settings.AUTH_USER_MODEL, verbose_name='Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField(verbose_name='Final Price')),
                ('sell_code', models.IntegerField(verbose_name='Sell Code')),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tax')),
                ('sold_date', models.DateTimeField(auto_now_add=True, verbose_name='Sold Date')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
                ('shopper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_shopper', to=settings.AUTH_USER_MODEL, verbose_name='Shopper')),
            ],
        ),
    ]
