# Generated by Django 5.0.7 on 2024-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('RE', 'Rent'), ('SE', 'Sell')], default='SE', max_length=10),
        ),
    ]
