# Generated by Django 5.0.7 on 2024-07-24 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Address'),
        ),
    ]
