# Generated by Django 5.0.7 on 2024-07-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0005_alter_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='realestate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='account.realestate', verbose_name='RealEstate'),
        ),
    ]
