# Generated by Django 5.0.7 on 2024-07-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_home_realestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='year_built',
            field=models.DateField(default='2024-01-01', verbose_name='Year Built'),
        ),
    ]
