# Generated by Django 5.0.7 on 2024-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_home_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='baths',
            field=models.PositiveIntegerField(default=1, verbose_name='Bath'),
        ),
    ]
