# Generated by Django 5.0.7 on 2024-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_home_garages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimages',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt'),
        ),
    ]
