# Generated by Django 5.0.7 on 2024-08-19 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_propertyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_property', to='main.home', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='sell',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_property', to='main.home', verbose_name='Property'),
        ),
    ]
