# Generated by Django 5.0.7 on 2024-08-19 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rent_property_sell_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.DateField(default=datetime.datetime(2024, 8, 19, 13, 29, 29, 748692, tzinfo=datetime.timezone.utc), verbose_name='Year Built'),
        ),
    ]
