# Generated by Django 5.0.7 on 2024-08-19 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_home_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Year Built'),
        ),
    ]
