# Generated by Django 5.0.7 on 2024-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_home_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='meter',
            field=models.PositiveIntegerField(verbose_name='Meter'),
        ),
    ]
